import Link from 'next/link';
import TerminalLayout from '../components/TerminalLayout';
import Typewriter from '../components/Typewriter';
import Button from '../components/ui/Button';

export default function Home() {
  return (
    <TerminalLayout>
      <div className="flex flex-col items-center justify-center min-h-[60vh] space-y-12">
        <div className="text-center space-y-4">
          <Typewriter
            text="INITIALIZING_DEVELOPER_FUTURE_ANALYSIS..."
            className="text-primary/70 text-sm"
          />
          <h1 className="text-4xl md:text-6xl font-black glitch-text tracking-tighter">
            DEV_LIFE_2035
          </h1>
          <p className="text-primary/60 max-w-lg mx-auto">
            The year is 2035. Most code is generated by sentient toasters.
            Where do you fit in the new world order?
          </p>
        </div>

        <div className="space-y-6 text-center w-full max-w-sm">
          <div className="p-4 border border-primary/20 bg-primary/5">
            <Typewriter
              text="SYSTEM READY. RUN DIAGNOSTIC? (Y/N)"
              delay={1500}
              className="mb-8"
            />

            <div className="flex gap-4 justify-center">
              <Link href="/quiz" className="w-full">
                <Button className="w-full">YES [ENTER]</Button>
              </Link>
              <Button variant="alert" className="w-full opacity-50 cursor-not-allowed">
                NO [ESC]
              </Button>
            </div>
          </div>

          <div className="text-[10px] opacity-20">
            CONNECTING TO NEURAL_NET_V4.2.1... ENCRYPTED
          </div>
        </div>
      </div>
    </TerminalLayout>
  );
}
